// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlGxbLoJXwC6QQRVGLC44hqiqB41Pe-Q4',
    appId: '1:1062140155973:android:b249abb36e3a1c82e86b2c',
    messagingSenderId: '1062140155973',
    projectId: 'appfirebase-2dcd0',
    databaseURL: 'https://appfirebase-2dcd0.firebaseio.com',
    storageBucket: 'appfirebase-2dcd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcU_wXZFt-ZytPcaz5zQTbqk9v3jTRWXc',
    appId: '1:1062140155973:ios:d7dfb7ecc0c80da1e86b2c',
    messagingSenderId: '1062140155973',
    projectId: 'appfirebase-2dcd0',
    databaseURL: 'https://appfirebase-2dcd0.firebaseio.com',
    storageBucket: 'appfirebase-2dcd0.appspot.com',
    iosClientId: '1062140155973-074vee05vklvcq4dn6rt913iots8agns.apps.googleusercontent.com',
    iosBundleId: 'com.jsonKim.firebaseTest',
  );
}
